#!/usr/bin/env python3
"""Generate a Manticore boot-stream memory image for the KCU105 JTAG flow.

Produces a text file of 32-bit hex words (one per line) that run_kcu105.tcl writes
into the on-chip BRAM. The boot stream format is taken directly from the on-chip
bootloader, Programmer.scala (StreamDest -> StreamBodyLength -> StreamInstruction* ->
StreamEpilogueLength -> StreamSleepLength), repeated for every PE:

    [ (dest_y << 8) | dest_x ]      # 16-bit dest word
    [ body_length ]                 # number of 64-bit instructions
    [ inst0[15:0] ][ inst0[31:16] ][ inst0[47:32] ][ inst0[63:48] ]   # 4 words / instr
    ...
    [ epilogue_length ]             # expected number of receives
    [ sleep_length ]                # initial per-core sleep

The countdown phase is generated by hardware, NOT part of the image (Programmer.scala
Phase.StreamCountDown reads no memory).

All values are 16-bit words; two 16-bit words are packed little-endian into each
32-bit output word (low word first) to match the 32-bit JTAG-to-AXI writes.

NOTE: the exact program semantics (instruction encodings, epilogue/sleep, and the
addressing units for GlobalMemoryInstructionBase / DramBank0Base) must be confirmed
on hardware. This generator nails the *container* format; the instructions below are
a placeholder skeleton to be filled in for the trivial reproducer.
"""
import argparse
import sys


def pe_block(x, y, instrs, epilogue, sleep):
    """16-bit words for one PE. instrs = list of 64-bit ints."""
    w = [((y & 0xFF) << 8) | (x & 0xFF), len(instrs) & 0xFFFF]
    for ins in instrs:
        w += [ins & 0xFFFF, (ins >> 16) & 0xFFFF, (ins >> 32) & 0xFFFF, (ins >> 48) & 0xFFFF]
    w += [epilogue & 0xFFFF, sleep & 0xFFFF]
    return w


def build_image(dimx, dimy, programs, instr_base_words=0):
    """programs: dict (x,y) -> (instrs, epilogue, sleep). Order: x fastest, then y.

    Returns the full BRAM image as a list of 16-bit words, with the boot stream
    placed at `instr_base_words`. Low memory (< instr_base_words) is left zeroed
    for program data / results.
    """
    stream = []
    for y in range(dimy):
        for x in range(dimx):
            instrs, epi, slp = programs[(x, y)]
            stream += pe_block(x, y, instrs, epi, slp)
    image = [0] * instr_base_words + stream
    return image


def pack32(words16):
    out = []
    for i in range(0, len(words16), 2):
        lo = words16[i] & 0xFFFF
        hi = (words16[i + 1] & 0xFFFF) if i + 1 < len(words16) else 0
        out.append(lo | (hi << 16))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dimx", type=int, default=2)
    ap.add_argument("--dimy", type=int, default=2)
    ap.add_argument("--instr-base-words", type=int, default=0)
    ap.add_argument("--nops", type=int, default=4,
                    help="number of NOP instructions in each PE's per-virtual-cycle body")
    ap.add_argument("--sleep", type=int, default=10)
    ap.add_argument("-o", "--out", default="image.hex")
    args = ap.parse_args()

    # ---- trivial boot/schedule test program ------------------------------
    # Each PE runs `--nops` NOPs per virtual cycle (NOP = opcode 0 = the all-zero
    # 64-bit instruction), expects 0 receives (epilogue 0), small initial sleep.
    # This exercises the whole boot -> BSP-schedule -> virtual-cycle-count path
    # without depending on ALU/global-memory encodings; the run is terminated by
    # the timeout in ScheduleConfig (-> EXCEPTION_TIMEOUT 0x10000, ap_done).
    nop = 0x0000000000000000
    body = [nop] * args.nops
    programs = {(x, y): (body, 0, args.sleep)
                for y in range(args.dimy) for x in range(args.dimx)}

    image16 = build_image(args.dimx, args.dimy, programs, args.instr_base_words)
    words32 = pack32(image16)
    with open(args.out, "w") as f:
        for w in words32:
            f.write("%08x\n" % (w & 0xFFFFFFFF))
    print("wrote %d 32-bit words to %s; instr_base_words=%d" %
          (len(words32), args.out, args.instr_base_words), file=sys.stderr)
    print("pass instr_base_words=%d to run_kcu105.tcl" % args.instr_base_words, file=sys.stderr)


if __name__ == "__main__":
    main()
