#!/usr/bin/env python3
"""Turn a manticore-compiler output (manifest.json + exec.bin's) into a flat BRAM
image + a JTAG-to-AXI run script, replicating what manticore-runtime does for XRT.

The runtime (manticore-manager.cpp) lays global memory out as:
  num_words = max(userGlobalMemoryBase, max(gm.base+gm.size))   # reserved + sim memories
  for each binary in (initializers..., main):
      binary.base = num_words ; num_words += len(binary_words)
Each exec.bin is a stream of little-endian 16-bit words (the per-PE boot stream the
on-chip Programmer reads). The sim memories + reserved region are zero in the image and
are populated at runtime by the initializer programs.

Run sequence (per runtime): DramBank0Base=0; run each initializer (FINISH), then main;
on FLUSH (a $display) do cache-flush + resume; classify the final eid via the manifest.

Performance notes (JTAG-over-hw_server is slow ~tens of ms/transaction):
  * the image is written with AXI BURST transactions (256 beats, 1 KiB-aligned so a burst
    never crosses a 4 KiB boundary), skipping all-zero chunks (BRAM powers up to 0).
  * per-cycle resume rewrites only ap_start (base/schedule are sticky AxiSlave registers)
    and polls leanly (one read after a short settle).

Outputs (into --outdir):
  image.mem : "<addr_hex> <len> <concatenated-beats-hex>" per burst (beat0 = lowest addr,
              rightmost in the hex string, matching create_hw_axi_txn -data LSB-first)
  run.tcl   : self-contained Vivado hw_manager script (program + load + run + verify)
"""
import argparse
import json
import os
import struct
import sys

CHUNK = 256  # AXI4 max burst beats; 256*4=1KiB, 1KiB-aligned => never crosses 4KiB


def read_binwords(path):
    with open(path, "rb") as f:
        data = f.read()
    assert len(data) % 2 == 0, f"{path}: odd byte count"
    return list(struct.unpack("<%dH" % (len(data) // 2), data))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("manifest")
    ap.add_argument("--outdir", default=".")
    ap.add_argument("--ctrl-base", type=lambda v: int(v, 0), default=0x00100000)
    ap.add_argument("--mem-base", type=lambda v: int(v, 0), default=0x0)
    ap.add_argument("--init-timeout", type=int, default=1000000)
    ap.add_argument("--main-timeout", type=int, default=50000000)
    ap.add_argument("--max-flushes", type=int, default=100000)
    ap.add_argument("--bitfile", default="/home/lucas/manticore/manticore_kcu105_2x2.bit")
    args = ap.parse_args()

    with open(args.manifest) as f:
        m = json.load(f)
    mdir = os.path.dirname(os.path.abspath(args.manifest))
    resolve = lambda p: p if os.path.isabs(p) else os.path.join(mdir, p)

    dimx, dimy = m["dimx"], m["dimy"]
    num_words = int(m.get("base", 0x4000))
    for gm in m.get("memories", []):
        num_words = max(num_words, int(gm["base"]) + int(gm["size"]))

    bins = []  # [name, base_words, words, is_init]
    for i, p in enumerate(m.get("initializers", [])):
        w = read_binwords(resolve(p))
        bins.append([f"init_{i}", num_words, w, True])
        num_words += len(w)
    mw = read_binwords(resolve(m["program"]))
    bins.append(["main", num_words, mw, False])
    num_words += len(mw)

    img16 = [0] * num_words
    for _, base, w, _ in bins:
        img16[base:base + len(w)] = w

    # pack to 32-bit little-endian
    n32 = (num_words + 1) // 2
    img32 = [0] * n32
    for i in range(n32):
        lo = img16[2 * i]
        hi = img16[2 * i + 1] if 2 * i + 1 < num_words else 0
        img32[i] = lo | (hi << 16)

    # The JTAG-to-AXI master is AXI4-Lite (no bursts), so write per 32-bit word. BRAM
    # powers up to 0, so only non-zero words need writing.
    os.makedirs(args.outdir, exist_ok=True)
    nbursts = nbeats = 0
    with open(os.path.join(args.outdir, "image.mem"), "w") as f:
        for i in range(n32):
            if img32[i]:
                f.write("%08x %08x\n" % (args.mem_base + i * 4, img32[i]))
                nbursts += 1
                nbeats += 1

    exc = {int(e["eid"]): e["type"] for e in m.get("exceptions", [])}
    total_kib = (num_words * 2 + 1023) // 1024
    print(f"dimx={dimx} dimy={dimy}  total={num_words} words ({total_kib} KiB)  "
          f"bursts={nbursts} beats={nbeats}", file=sys.stderr)
    for name, base, w, is_init in bins:
        print(f"  {name:8s} base={base} ({len(w)} words){' [init]' if is_init else ''}",
              file=sys.stderr)
    if total_kib > 256:
        print(f"WARNING: image needs {total_kib} KiB > 256 KiB BRAM — rebuild with larger mem_kib.",
              file=sys.stderr)

    # ---- generate run.tcl --------------------------------------------------
    CB = args.ctrl_base
    L = []
    a = L.append
    a("# auto-generated by run_manifest.py")
    a("set bitfile {%s}" % args.bitfile)
    a("set memfile [file join [file dirname [info script]] image.mem]")
    a("set CB %d" % CB)
    a("set MAINBASE %d" % bins[-1][1])
    a("array set EXC {%s}" % " ".join(f"{eid} {t}" for eid, t in exc.items()))
    a("open_hw_manager; connect_hw_server -url localhost:3121")
    a("current_hw_target [lindex [get_hw_targets] 0]; open_hw_target")
    a("set dev [get_hw_devices xcku040_0]; current_hw_device $dev")
    a("set_property PROGRAM.FILE $bitfile $dev; program_hw_devices $dev; refresh_hw_device -quiet $dev")
    a("set axi [lindex [get_hw_axis] 0]")
    a("proc h8 {v} { return [format %08x [expr {$v & 0xffffffff}]] }")
    a("proc w32 {a d} { global axi; catch {delete_hw_axi_txn [get_hw_axi_txns tw]};"
      " create_hw_axi_txn tw $axi -address [h8 $a] -data [h8 $d] -type write;"
      " run_hw_axi -quiet [get_hw_axi_txns tw] }")
    a("proc r32 {a} { global axi; catch {delete_hw_axi_txn [get_hw_axi_txns tr]};"
      " create_hw_axi_txn tr $axi -address [h8 $a] -type read -len 1;"
      " run_hw_axi -quiet [get_hw_axi_txns tr]; return [expr 0x[get_property DATA [get_hw_axi_txns tr]]] }")
    a("proc w64 {a v} { w32 $a [expr {$v & 0xffffffff}]; w32 [expr {$a+4}] [expr {($v>>32)&0xffffffff}] }")
    # load the image (per 32-bit word; AXI4-Lite master => no bursts)
    a("puts {Loading image...}")
    a("set fh [open $memfile r]; set nb 0")
    a("foreach ln [split [read $fh] \"\\n\"] { set ln [string trim $ln]; if {$ln eq {}} continue;"
      " lassign $ln aa dd; w32 [expr 0x$aa] [expr 0x$dd]; incr nb }")
    a("close $fh; puts \"loaded $nb words\"")
    # verify a couple of words against the image
    for probe_base in [bins[-1][1]]:
        a('puts "verify main\\[0\\]=[h8 [r32 [expr {%d*2}]]] (expect %08x)"'
          % (probe_base, (img16[probe_base] | (img16[probe_base + 1] << 16))))
    a("w64 [expr {$CB+0x90}] 0  ;# DramBank0Base = 0")
    # lean poll: device finishes a (re)start in microseconds; settle then read once, retry a few
    a("proc wait_done {} { global CB; for {set p 0} {$p<200} {incr p} { set c [r32 [expr {$CB+0x00}]];"
      " if {(($c>>1)&1)||(($c>>2)&1)} { return $c }; after 2 }; return $c }")
    a("proc classify {eid} { global EXC; if {$eid>0xffff} {return TIMEOUT};"
      " if {[info exists EXC($eid)]} {return $EXC($eid)}; return unknown }")
    a("proc run_cmd {name base cmdword} { global CB")
    a("  w64 [expr {$CB+0x6c}] $cmdword")
    a("  w64 [expr {$CB+0x84}] $base")
    a("  w32 [expr {$CB+0x00}] 1")
    a("  wait_done; set eid [r32 [expr {$CB+0x10}]]; set vc [r32 [expr {$CB+0x38}]]")
    a("  set k [classify $eid]")
    a("  puts [format {  %-8s eid=0x%05x vcycles=%d -> %s} $name $eid $vc $k]; return [list $eid $k vc $vc] }")
    a("proc start_cmd {to} { return [expr {(1<<63)|$to}] }")
    a("proc resume_cmd {to} { return [expr {(1<<63)|(1<<56)|$to}] }")
    a("proc flush_cmd {} { return [expr {(2<<56)}] }")
    for name, base, w, is_init in bins:
        if is_init:
            a('lassign [run_cmd %s %d [start_cmd %d]] eid kind' % (name, base, args.init_timeout))
    a('lassign [run_cmd main $MAINBASE [start_cmd %d]] eid kind' % args.main_timeout)
    # Decode one trace record (RF-write $display) from global memory words 0..6
    # (the manifest fmt offsets), written there by the design and flushed to BRAM.
    a('proc read_trace {} { global MEM_BASE')
    a('  set w0 [r32 0]; set w1 [r32 4]; set w2 [r32 8]; set w3 [r32 12]')
    a('  set pc [expr {($w0 & 0xffff) | (($w0>>16)<<16)}]')
    a('  set instr [expr {($w1 & 0xffff) | (($w1>>16)<<16)}]')
    a('  set rg [expr {$w2 & 0xffff}]')
    a('  set val [expr {(($w2>>16)&0xffff) | (($w3&0xffff)<<16)}]')
    a('  return [format {%08x %08x: RF[%2d] <= %d} $pc $instr $rg $val] }')
    # FLUSH/resume loop. On each FLUSH: cache-flush (pushes trace to BRAM), decode the
    # $display record (TRACE lines, comparable to the interpreter golden), then resume.
    a('set MEM_BASE 0')
    a('set guard 0')
    a('while {$kind eq "FLUSH" && $guard < %d} {' % args.max_flushes)
    a('  w64 [expr {$CB+0x6c}] [flush_cmd]; w32 [expr {$CB+0x00}] 1; wait_done')
    a('  puts "TRACE [read_trace]"')
    a('  w64 [expr {$CB+0x6c}] [resume_cmd %d]; w32 [expr {$CB+0x00}] 1; wait_done' % args.main_timeout)
    a('  set eid [r32 [expr {$CB+0x10}]]; set kind [classify $eid]')
    a('  incr guard }')
    a('set vc [r32 [expr {$CB+0x38}]]')
    a('puts "=== RESULT: $kind (eid=0x[format %x $eid]) vcycles=$vc after $guard flushes ==="')
    a('if {$kind eq "FINISH" || $kind eq "STOP"} { puts "PASS: simulation terminated normally ($kind)" } '
      'elseif {$kind eq "ASSERT"} { puts "FAIL: assertion failed" } '
      'else { puts "INCOMPLETE: $kind" }')
    a("close_hw_target")

    with open(os.path.join(args.outdir, "run.tcl"), "w") as f:
        f.write("\n".join(L) + "\n")
    print(f"wrote {args.outdir}/image.mem and {args.outdir}/run.tcl", file=sys.stderr)


if __name__ == "__main__":
    main()
